apiVersion: apps/v1
kind: Deployments
metadata:
  name: app-one
  namespace: api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one
          image: collins/app-one
          envFrom:
            - configMapRef:
                name: app-one-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: app-one-srv
  namespace: api
  labels:
    app: app-one

spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: app-one
