apiVersion: v1
kind: Service
metadata:
  name: backend

spec:
  type: LoadBalancer
  ports:
    - port: 80.  # The port is where the service is exposed
      targetPort: 80  # The targetPort for the pod or where the backend app is exposed
      nodePort: 30008
  selector:
    app: myapp
    type: backend