apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replica-set
  labels:
    app: myapp
    type: backend

spec:
  selector: # Selector is a label query over pods that should match the replica count. Label keys and values that must match in order to be controlled by this replica set. It must match the pod template's labels.
    matchLabels:
      app: myapp
      type: backend-app
  template:
    metadata:      
      name: myapp-pod 
      labels:      
        app: myapp
        type: backend-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

  replicas: 6
    